### PR TITLE
Joining

### PR DESCRIPTION
**Pull request by djrobstep**
- adds basic joining (found it sometimes useful to do this without needing a database)
- adds a `transposed` method
- modifies excel loader to use `data_only` parameter for speed
- fixes linting (uses git masters to support walrus operator), re-enables in build
- fixes build error from previous pull request
- adds an `ltrsort` method, which sorts columns from left to right
- adds nonesfirst/noneslast methods so you can sort stuff that has `None`s in it (useful for joining and ltrsort)

### CODE REVIEW

**Comment by jasongi-actu** [comment]
The deployments are still broked

**Comment by jasongi-actu** [comment]
https://xkcd.com/2180/

**Comment by djrobstep** [comment]
what's broken with the builds? i don't see a build for this branch (this branch should fix the current problem on master at least)

**Comment by jasongi-actu** [comment]
You've just fixed it, it's the poetry settings

**Pull request merged**
