### PR TITLE
Remove walrus

### PR DESCRIPTION
**Pull request by jasongi-actu**
Python 3.7 support still desired

### CODE REVIEW

**Comment by jasongi-actu** [comment]
@djrobstep I've had my heart broken twice this month. First Bernie now this.

**Comment by actuchicks** [comment]
I like walruses but this one is just a bit inconvenient

**Comment by jasongi-actu** [comment]
https://www.youtube.com/watch?v=t1Jm5epJr10

**Comment by djrobstep** [comment]
First walrus operator I ever used, gone like tears in the rain. Crying in da club right now

**Pull request merged**
